apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: AWS_REGION
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: platform-secrets-synced
    creationPolicy: Owner
  data:
    - secretKey: JIRA_EMAIL
      remoteRef:
        key: /xbrain-cdo5/ENV_NAME/jira_email
    - secretKey: JIRA_URL
      remoteRef:
        key: /xbrain-cdo5/ENV_NAME/jira_url
    - secretKey: JIRA_USER
      remoteRef:
        key: /xbrain-cdo5/ENV_NAME/jira_user
    - secretKey: JIRA_PROJECT_KEY
      remoteRef:
        key: /xbrain-cdo5/ENV_NAME/jira_project_key
    - secretKey: JIRA_TOKEN
      remoteRef:
        key: /xbrain-cdo5/ENV_NAME/jira_api_key
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: /xbrain-cdo5/ENV_NAME/slack_webhook_url
    - secretKey: SQS_QUEUE_URL
      remoteRef:
        key: /xbrain-cdo5/ENV_NAME/sqs_queue_url
