apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token-sync
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" # Đảm bảo Secret được tạo trước khi AppSet chạy
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: tf1-aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: github-token # Tên này phải khớp với secretName trong appset.yaml
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: /xbrain-cdo5/argocd/github_token
