name: Reusable TF Plan
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Environment name (sandbox, staging, prod)"
      tf_working_dir:
        required: true
        type: string
        description: "Terraform working directory"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: AWS Auth
        uses: ./.github/actions/aws-auth-oidc
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.IAM_ROLE_ARN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        working-directory: ${{ inputs.tf_working_dir }}
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: ${{ inputs.tf_working_dir }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ inputs.tf_working_dir }}
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ${{ inputs.tf_working_dir }}
        run: terraform plan -out=tfplan -input=false -no-color
        continue-on-error: true

      - name: Export Plan to JSON
        working-directory: ${{ inputs.tf_working_dir }}
        run: terraform show -json tfplan > plan.json

      - name: Comment PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          script: |
            const output = `#### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan for **${{ inputs.environment }}**</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Environment: \`${{ inputs.environment }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
